[package]
name = "discord2"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = {version ="0.9.2", package="gtk4"}
reqwest = { version = "0.12.8", features = ["blocking"] }
serde_json = "1.0.128"
yaml-rust = "0.4.5"
